
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gaurav
 */
public class HomeScreen extends javax.swing.JDialog {

    TranslateService ts = new TranslateService();
    String user1,user2,translation,transFunc,u1Name = "User 1",u2Name = "User 2";
    Language l = new Language();
    String u1,u2,d1=null,d2="en",lastLanguage="en";
    int flag = 0,flag1= 0;
    int u1Error=0;int u2Error=0;
    int survey=0,indi1=0,indi2=0;

    
    /**    System.out.println(Language.English);

     * Creates new form HomeScreen
     */
    public HomeScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        u1Name = JOptionPane.showInputDialog("User 1 \n Enter Name: ");
        u2Name = JOptionPane.showInputDialog("User 2 \n Enter Name: ");
        er1.setVisible(false);
        er2.setVisible(false);
        if(u1Name == null || u1Name.equals(""))
            u1Name = "User 1";
            jLabel2.setText(u1Name);
        if(u2Name==null || u2Name.equals(""))
            u2Name = "User 2";
        jLabel3.setText(u2Name);
        jToggleButton1.setVisible(false);
        
    }
    public String callTranslate(String text,String target,String source){
        try {
            transFunc = ts.translate(text,target,source);
        } catch (IOException ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        return transFunc;
    }
    public String callTrans(String text,String target,String source){
        try {
            transFunc = ts.trans(text,target,source);
        } catch (IOException ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        return transFunc;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        u1TextArea = new javax.swing.JTextArea();
        u1TextField = new javax.swing.JTextField();
        u2TextField = new javax.swing.JTextField();
        u1Button = new javax.swing.JButton();
        u2Button = new javax.swing.JButton();
        u1Language = new javax.swing.JComboBox<String>();
        u2Language = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        completeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        u2TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setText(u2Name);
        jToggleButton1 = new javax.swing.JToggleButton();
        er1 = new javax.swing.JLabel();
        er2 = new javax.swing.JLabel();
        languageDetected = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        User1 = new javax.swing.JMenuItem();
        User2 = new javax.swing.JMenuItem();
        rs = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Translator v1.0.0");
        setBackground(new java.awt.Color(255, 255, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        u1TextArea.setEditable(false);
        u1TextArea.setBackground(new java.awt.Color(0, 0, 153));
        u1TextArea.setColumns(32);
        u1TextArea.setForeground(new java.awt.Color(255, 153, 51));
        u1TextArea.setLineWrap(true);
        u1TextArea.setRows(10);
        u1TextArea.setToolTipText("");
        u1TextArea.setWrapStyleWord(true);
        u1TextArea.setBorder(null);
        jScrollPane1.setViewportView(u1TextArea);
        u1TextArea.getAccessibleContext().setAccessibleName("");

        u1TextField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        u1TextField.setForeground(new java.awt.Color(153, 153, 153));
        u1TextField.setText("Enter your text here");
        u1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                u1TextFieldFocusGained(evt);
            }
        });
        u1TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u1TextFieldMouseClicked(evt);
            }
        });
        u1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u1TextFieldActionPerformed(evt);
            }
        });

        u2TextField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        u2TextField.setForeground(new java.awt.Color(153, 153, 153));
        u2TextField.setText("Enter your text here");
        u2TextField.setToolTipText("");
        u2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                u2TextFieldFocusGained(evt);
            }
        });
        u2TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u2TextFieldMouseClicked(evt);
            }
        });
        u2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u2TextFieldActionPerformed(evt);
            }
        });

        u1Button.setText("Send");
        u1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u1ButtonActionPerformed(evt);
            }
        });

        u2Button.setText("Send");
        u2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u2ButtonActionPerformed(evt);
            }
        });

        u1Language.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "English", "Hindi", "ChineseSimplified", "ChineseTraditional", "Afrikaans", "Spanish", "Albanian", "Arabic", "Azerbaijani", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "Croatian", "Czech", "Danish", "Dutch", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "HaitianCreole", "Hebrew", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        u1Language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u1LanguageActionPerformed(evt);
            }
        });

        u2Language.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Afrikaans", "Albanian", "Arabic", "Azerbaijani", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "ChineseSimplified", "ChineseTraditional", "Croatian", "Czech", "Danish", "Dutch", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "HaitianCreole", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        u2Language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u2LanguageActionPerformed(evt);
            }
        });

        jButton1.setText("<Error>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<Error>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        completeButton.setText("Complete Interaction");
        completeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeButtonActionPerformed(evt);
            }
        });

        u2TextArea.setEditable(false);
        u2TextArea.setBackground(new java.awt.Color(255, 153, 51));
        u2TextArea.setColumns(32);
        u2TextArea.setForeground(new java.awt.Color(0, 0, 153));
        u2TextArea.setLineWrap(true);
        u2TextArea.setRows(7);
        u2TextArea.setWrapStyleWord(true);
        u2TextArea.setBorder(null);
        jScrollPane2.setViewportView(u2TextArea);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Translator");

        jLabel2.setText("User 1");

        jLabel3.setText("User 2");

        jToggleButton1.setText("Complete Survey");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        er1.setForeground(new java.awt.Color(255, 0, 0));
        er1.setText("Error Recorded!");

        er2.setForeground(new java.awt.Color(255, 0, 0));
        er2.setText("Error Recorded!");

        languageDetected.setForeground(new java.awt.Color(51, 204, 0));
        languageDetected.setText("Language Detected: ");

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.setOpaque(false);

        jMenu1.setBorder(null);
        jMenu1.setMnemonic('f');
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menu.add(jMenu1);

        jMenu2.setMnemonic('e');
        jMenu2.setText("Edit");

        jMenu3.setText("Users Info");

        User1.setText("User 1");
        User1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User1ActionPerformed(evt);
            }
        });
        jMenu3.add(User1);

        User2.setText("User 2");
        User2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User2ActionPerformed(evt);
            }
        });
        jMenu3.add(User2);

        jMenu2.add(jMenu3);

        rs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        rs.setText("Reset");
        rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsActionPerformed(evt);
            }
        });
        jMenu2.add(rs);

        menu.add(jMenu2);

        jMenu4.setMnemonic('v');
        jMenu4.setText("View");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("User 1");
        jCheckBoxMenuItem1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem1ItemStateChanged(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("User 2");
        jCheckBoxMenuItem2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem2ItemStateChanged(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Both");
        jCheckBoxMenuItem3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem3ItemStateChanged(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem3);

        menu.add(jMenu4);

        setJMenuBar(menu);
        menu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completeButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(u1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(u1Button))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(languageDetected)
                                .addComponent(u1Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(er1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(er2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(u2Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(u2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(u2Button))))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completeButton)
                    .addComponent(jToggleButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(u1Button)
                                    .addComponent(u1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(u1Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(u2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(u2Button))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(u2Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))))
                        .addGap(18, 18, 18)
                        .addComponent(languageDetected)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(er2)
                            .addComponent(er1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton3)
                .addGap(46, 46, 46))
        );

        getAccessibleContext().setAccessibleDescription("Helps users speaking diggerent Languages interact ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void u1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u1ButtonActionPerformed
        //--------------------------------------------SEND 1---------------------------------------------------
       u1TextFieldActionPerformed(evt);
        /*er1.setVisible(false);
        er2.setVisible(false);
       if(u1TextField.getText().equals("Enter your text here")&& indi1 == 0){
            indi1 = 1;
            u1TextField.setText("");
            u1TextField.setForeground(Color.black);
            
            u1TextField.setFont(u1TextField.getFont().deriveFont(Font.PLAIN));
        }
         
        if(u1TextField.getText().equals("")){
            
        }
        else{
             
            user1 = u1TextField.getText();
                
            if(d1==d2){
                JOptionPane.showMessageDialog(rootPane,"Please select different lanugages");
                u1TextField.setText("");
                u2TextField.setText("");
            }
            else{
                for(int i=1;i<=(u1TextArea.getColumns()-user1.length()+15);i++)
                u1TextArea.append("  ");
            u1TextArea.append("You: "+user1+"\n");
            translation = callTranslate(user1, d2, d1);
            d1 = ts.obtainedSource;
            languageDetected.setText("Language Detected : "+"'"+d1+"'");
            //u1TextArea.setFont(new Font("Serif", Font.ITALIC, 16));
            u2TextArea.append(u1Name+":  "+translation+"\n");
            // System.out.println("U1: "+user1.length()+" "+"UT2: "+u2TextArea.getColumns());
            u1TextField.setText("");
            }
        }*/
    }//GEN-LAST:event_u1ButtonActionPerformed

    private void u2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u2ButtonActionPerformed
        //----------------------------------------------SEND 2-----------------------------------------------------
        u2TextFieldActionPerformed(evt);
        /*if(u2TextField.getText().equals("Enter your text here")&& indi2 == 0){
            indi2 = 1;
            u2TextField.setText("");
            u2TextField.setForeground(Color.black);
            
            u2TextField.setFont(u2TextField.getFont().deriveFont(Font.PLAIN));
        }
        er1.setVisible(false);
        er2.setVisible(false);
        if(u2TextField.getText().equals("Enter your text here"))
            u2TextField.setText("");
        
        if(u2TextField.getText().equals("")){
            
        }
        else{
            user2 = u2TextField.getText();
            
            if(d1 == null){
                d1 = ts.obtainedSource;
                if(d1.equals(d2))
                    d1 = lastLanguage;
                flag1 = 1;
            }
            if(d1==d2){
                JOptionPane.showMessageDialog(rootPane,"Please select different lanugages");
                u1TextField.setText("");
                u2TextField.setText("");
            }
            else{
                u2TextArea.append("You: "+user2+"\n");
                for(int i=1;i<=(u2TextArea.getColumns()-user2.length()+15);i++)
                u2TextArea.append("  ");       
                translation = callTranslate(user2, d1, d2);           
                u1TextArea.append(u2Name+":  "+translation+"\n");
                
                //System.out.println("U2: "+user2.length()+" "+"UT1: "+u1TextArea.getColumns());
                u2TextField.setText("");
            }
            if(flag1==1){
                    d1=null;
                    flag1 = 0;
                }
        }*/
    }//GEN-LAST:event_u2ButtonActionPerformed

    private void u1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u1TextFieldActionPerformed
//---------------------------------------------------------TEXT 1---------------------------------------------
        if( indi1 == 0){
            indi1 = 1;
            u1TextField.setText("");
            u1TextField.setForeground(Color.black);
            
            u1TextField.setFont(u1TextField.getFont().deriveFont(Font.PLAIN));
        }
        er1.setVisible(false);
        er2.setVisible(false);
        if(u1TextField.getText().equals("")){
            
        }
        else{
            user1 = u1TextField.getText();
                for(int i=1;i<=(u1TextArea.getColumns()-user1.length()+10);i++)//---------------------------------
                    u1TextArea.append("  ");
            if(d1 == d2){
                /*JOptionPane.showMessageDialog(rootPane,"Please select different lanugages");
                u1TextField.setText("");
                u2TextField.setText("");*/
                u1TextArea.append("You: "+user1+"\n");
                u2TextArea.append(u1Name+":  "+user1+"\n");
                u1TextField.setText("");
            }
            else{
                /*user1 = u1TextField.getText();
                for(int i=1;i<=(u1TextArea.getColumns()-user1.length()+15);i++)
                    u1TextArea.append("  ");*/
                u1TextArea.append("You: "+user1+"\n");
                translation = callTranslate(user1, d2, d1);
                String dd = ts.obtainedSource;
            languageDetected.setText("Last AutoDetect : "+"'"+dd+"'");
                //System.out.println(ts.obtainedSource);
                //--------------u1TextArea.setForeground(Color.green);
                u2TextArea.append(u1Name+":  "+translation+"\n");
                u1TextField.setText("");
            }
        }
    }//GEN-LAST:event_u1TextFieldActionPerformed

    private void u2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u2TextFieldActionPerformed
        // ----------------------------------------------TEXT 2--------------------------------------------------------
        if(indi2 == 0){
            indi2 = 1;
            u2TextField.setText("");
            u2TextField.setForeground(Color.black);
            
            u2TextField.setFont(u2TextField.getFont().deriveFont(Font.PLAIN));
        }
        er1.setVisible(false);
        er2.setVisible(false);
        if(u2TextField.getText().equals("")){
            
        }
        else{
            user2 = u2TextField.getText();
            
            if(d1 == null){
                d1 = ts.obtainedSource;
                if(d1==null)
                    d1 = lastLanguage;
                flag1 = 1;
            }
             for(int i=1;i<=(u2TextArea.getColumns()-user2.length()+10);i++)//-------------------------------------------
                    u2TextArea.append("  ");
            if(d1.equals(d2)){
                /*JOptionPane.showMessageDialog(rootPane,"Please select different lanugages");
                u1TextField.setText("");
                u2TextField.setText("");*/
                u2TextArea.append("You: "+user2+"\n");
                u1TextArea.append(u1Name+":  "+user2+"\n");
                u2TextField.setText("");
            }
            else{
                
                for(int i=1;i<=(u2TextArea.getColumns()-user2.length()+15);i++)
                    u2TextArea.append("  ");
                u2TextArea.append("You: "+user2+"\n");
                //System.out.println("d1: "+d1+" d2: "+d2);
                translation = callTranslate(user2, d1, d2);
                u1TextArea.append(u2Name+":  "+translation+"\n");
                
            
                u2TextField.setText("");
            }
            if(flag1==1){
                    d1=null;
                    flag1 = 0;
                }
        }
    }//GEN-LAST:event_u2TextFieldActionPerformed

    private void u1LanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u1LanguageActionPerformed
        er1.setVisible(false);
        er2.setVisible(false);
        u1=u1Language.getSelectedItem().toString();
        d1 = Language.Languages.get(u1);
        if(u1.equals("Auto"))
            languageDetected.setVisible(true);
        else
            languageDetected.setVisible(false);
        //u2TextArea.append(u1);
    }//GEN-LAST:event_u1LanguageActionPerformed

    private void u2LanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u2LanguageActionPerformed
        er1.setVisible(false);
        er2.setVisible(false);
        u2=u2Language.getSelectedItem().toString();
        d2 = Language.Languages.get(u2);
        
    }//GEN-LAST:event_u2LanguageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        u1Error++; 
        er1.setVisible(true);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        u2Error++;
        er2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void completeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeButtonActionPerformed
        survey = 1;
        if(u1Name==null|| u1Name.equals(""))
            u1Name = "User 1";
        if(u2Name==null|| u2Name.equals(""))
            u2Name = "User 2";
        JOptionPane.showMessageDialog(rootPane, "Number of errors reported \n\t"+u1Name+" : "+u1Error+"\n\t"+u2Name+" : "+u2Error+"\n\nThank You\nNow you can Press COPMPLETE SURVEY button   ");
        try 
        {
            Desktop.getDesktop().browse(new URL("https://ufl.qualtrics.com/SE/?SID=SV_42sF9wygbzmP4oZ").toURI());
        }           
        catch (URISyntaxException | IOException e) {}
        
        
        completeButton.setVisible(false);
        jToggleButton1.setVisible(true);
    }//GEN-LAST:event_completeButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void User1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User1ActionPerformed
       u1Name= JOptionPane.showInputDialog("User 1:\nEnter Name: ");
       if(u1Name.equals(null))
           jLabel2.setText("User 1");
       else
            jLabel2.setText(u1Name);
    }//GEN-LAST:event_User1ActionPerformed

    private void rsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsActionPerformed
        u1TextField.setText("");
        u2TextField.setText("");
        u1TextArea.setText("");
        u2TextArea.setText("");
    }//GEN-LAST:event_rsActionPerformed

    private void jCheckBoxMenuItem1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ItemStateChanged
       
        if(evt.getStateChange()==ItemEvent.SELECTED ) 
           u1TextArea.setVisible(true);
        else{
            flag = 1;           
            u1TextArea.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ItemStateChanged

    private void jCheckBoxMenuItem2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ItemStateChanged
        
        if(evt.getStateChange()==ItemEvent.SELECTED ) 
           u2TextArea.setVisible(true);
       else
           u2TextArea.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem2ItemStateChanged

    private void jCheckBoxMenuItem3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ItemStateChanged
       if(evt.getStateChange()==ItemEvent.SELECTED ) {
           jCheckBoxMenuItem2.setState(true);
           jCheckBoxMenuItem1.setState(true);
       }
       else{
           jCheckBoxMenuItem2ItemStateChanged(evt);
           jCheckBoxMenuItem1ItemStateChanged(evt);
           jCheckBoxMenuItem2.setState(false);
           jCheckBoxMenuItem1.setState(false);
       }                                    
    }//GEN-LAST:event_jCheckBoxMenuItem3ItemStateChanged

    private void User2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User2ActionPerformed
        u2Name = JOptionPane.showInputDialog("User 2:\nEnter Name: ");
        if(u2Name.equals(null))
            jLabel3.setText("User 2");
        else
            jLabel3.setText(u2Name);
    }//GEN-LAST:event_User2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(survey==1)
            System.exit(0);
        else
            JOptionPane.showMessageDialog(rootPane, "Please Complete Interaction First");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void u1TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u1TextFieldMouseClicked
        if(u1TextField.getText().equals("Enter your text here")&& indi1 == 0){
            indi1 = 1;
            u1TextField.setText("");
            u1TextField.setForeground(Color.black);
            
            u1TextField.setFont(u1TextField.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_u1TextFieldMouseClicked

    private void u2TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u2TextFieldMouseClicked
        if(u2TextField.getText().equals("Enter your text here") && indi2 == 0){
            indi2 = 1;
            u2TextField.setText("");
            u2TextField.setForeground(Color.black);

            u2TextField.setFont(u2TextField.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_u2TextFieldMouseClicked

    private void u1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_u1TextFieldFocusGained
        if(u1TextField.getText().equals("Enter your text here")&& indi1 == 0){
            indi1 = 1;
            u1TextField.setText("");
            u1TextField.setForeground(Color.black);
            
            u1TextField.setFont(u1TextField.getFont().deriveFont(Font.PLAIN));
            er1.setVisible(false);
            er2.setVisible(false);
        }
    }//GEN-LAST:event_u1TextFieldFocusGained

    private void u2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_u2TextFieldFocusGained
        if(u2TextField.getText().equals("Enter your text here")&& indi2 == 0){
            indi2 = 1;
            u2TextField.setText("");
            u2TextField.setForeground(Color.black);
            
            u2TextField.setFont(u2TextField.getFont().deriveFont(Font.PLAIN));
            er1.setVisible(false);
            er2.setVisible(false);
        }
    }//GEN-LAST:event_u2TextFieldFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        u1TextField.setText("");
        u2TextField.setText("");
        u1TextArea.setText("");
        u2TextArea.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeScreen dialog = new HomeScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem User1;
    private javax.swing.JMenuItem User2;
    private javax.swing.JButton completeButton;
    private javax.swing.JLabel er1;
    private javax.swing.JLabel er2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;

    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel languageDetected;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem rs;
    private javax.swing.JButton u1Button;
    private javax.swing.JComboBox<String> u1Language;
    private javax.swing.JTextArea u1TextArea;
    private javax.swing.JTextField u1TextField;
    private javax.swing.JButton u2Button;
    private javax.swing.JComboBox u2Language;
    private javax.swing.JTextArea u2TextArea;
    private javax.swing.JTextField u2TextField;
    // End of variables declaration//GEN-END:variables
}
